version: '3.8'
services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: simulator
    user: vortex
    privileged: true
    volumes:
      - "/dev:/dev"
    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host